version: '3.2'

services:
  backend_node:
    image: "node:12"
    volumes:
      - "./backend_node/:/home/node/app"
    expose:
      - "8082"
    command: bash -c "npm i && npm run dev"
    working_dir: /home/node/app
    ports:
      - 8082:8082
    links:
      - redis
    depends_on:
      - redis
    networks:
      - challenge

  frontend:
    image: "node:12"
    volumes:
      - "./frontend/:/home/node/app"
    expose:
      - "8080"
    command: bash -c "npm i && npm run serve"
    working_dir: /home/node/app
    ports:
      - 8080:8080
    links:
      - backend_node
    depends_on:
      - backend_node
    networks:
      - challenge

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/data
    networks:
      - challenge


networks:
  challenge:
    driver: bridge

volumes:
  redis:

